Fix brightness for 72x40 display
jamwaffles/ssd1306 pull request #141
Opened 2020-11-28 04:18 UTC by ew1abz

72x40 OLED display uses a slightly different driver IC - SSD1306B. The display has only ~30% brightness if the internal Iref is turned off. To fix it, we need to issue a new command for this specific model.

### Useful info:
- https://bitbanksoftware.blogspot.com/2019/06/how-much-current-do-oled-displays-use.html?showComment=1572526557125#c3707851226502222177
- https://github.com/olikraus/u8g2/issues/1047

2020-12-01 10:17 UTC, jamwaffles requested changes
Sorry for the delay. Looks good to me overall, just a small tweak to the changelog needed.

I haven't tested this on a physical device, so I'll take your word that the new config works :grin:

2020-12-01 10:17 UTC, jamwaffles commented on CHANGELOG.md
> +
Please add a link to the PR here. I also don't think we need to show added docs in the changelog.

```suggestion
### Fixed

- [#141](https://github.com/jamwaffles/ssd1306/pull/141) Brightness for 72x40 display.
```

2020-12-14 12:09 UTC, jamwaffles commented
Hey, can you rebase this again please? There's another conflict in the changelog.

I missed that you had update the PR. When you're ready for a review, please hit the <kbd>Request review</kbd> button so I get a notification :).

I tested this on my half-dead 72x40 display and nothing seems broken, so I'll get this merged once the conflict is resolved.

2020-12-15 07:53 UTC, ew1abz commented
No problem, James. I rebased and updated PR, ready for review.

2020-12-15 09:42 UTC, jamwaffles approved these changes
Looks good. Thanks!

2020-12-15 09:42 UTC, merged

2020-12-15 09:55 UTC, jamwaffles commented
This is released in [0.4.2](https://crates.io/crates/ssd1306/0.4.2)