Add DisplaySize configuration for 64x32 displays
jamwaffles/ssd1306 pull request #166
Opened 2022-08-13 14:45 UTC by carlossless

- [x] Check that you've added documentation to any new methods
- [x] Rebase from `master` if you're not already up to date
- [x] Add or modify an example if there are changes to the public API
- [ ] Add a `CHANGELOG.md` entry in the **Unreleased** section under the appropriate heading (**Added**, **Fixed**, **Changed**, etc)
- [x] Run `rustfmt` on the project with `cargo fmt --all` - CI will not pass without this step
- [ ] Check that your branch is up to date with master and that CI is passing once the PR is opened

## PR description

Adding a predefined configuration for 64x32 displays, commonly marketed as "0.49" OLED display" like [this panel](https://www.buydisplay.com/0-49-inch-oled-display-module-64x32-pixel-ssd1306-spi-i2c-white-on-black) or [this module](https://www.buydisplay.com/i2c-white-0-49-inch-oled-display-module-64x32-arduino-raspberry-pi).

2022-08-13 14:55 UTC, carlossless commented
@jamwaffles seems like the build is failing, but it's not due to the changes in this PR.

2022-08-14 10:50 UTC, jamwaffles requested changes
A very pedantic nit, otherwise LGTM. I don't have a display that size to test on so can I just confirm that `OFFSETX` should indeed be `32` and isn't a copypasta error?

Thanks for exercising the build too. I pushed a couple of fixes to the `master` branch, so if you could update this branch it should build again.

2022-08-14 10:50 UTC, jamwaffles commented on CHANGELOG.md
> +- [#166](https://github.com/jamwaffles/ssd1306/pull/166) Added DisplaySize configuration for 64x32 displays
```suggestion
- [#166](https://github.com/jamwaffles/ssd1306/pull/166) Added `DisplaySize` configuration for 64x32 displays
```

2022-08-14 14:20 UTC, carlossless commented
@jamwaffles oh yes, I have the given configuration running in "production".

<img src="https://user-images.githubusercontent.com/498906/184540929-02464e33-9c70-4d35-997f-0b07eb04d0c0.jpg" height="446" /><img src="https://user-images.githubusercontent.com/498906/184540931-a74fe41e-acbd-42be-b58c-e067500cdb54.jpg" height="446" />

For additional reference, other drivers have implemented the same offset: https://github.com/olikraus/u8g2/blob/master/csrc/u8x8_d_ssd1306_64x32.c#L159

2022-08-15 10:13 UTC, jamwaffles approved these changes
Sweet, thanks for confirming!

2022-08-15 10:13 UTC, merged

2022-08-15 10:29 UTC, jamwaffles commented
Released in [0.7.1](https://crates.io/crates/ssd1306/0.7.1).